# =============================================================================
# JABU-SAMS | app/celery_worker.py
# Phase 2: The Asynchronous Background Processing Engine.
#
# ARCHITECTURAL ROLE:
# This module is the "decompression chamber" for offline tablet sync bursts.
# When a tablet at the Main Gate reconnects after hours offline, it may dump
# thousands of queued scan events simultaneously. If the Flask API wrote all
# of these directly to PostgreSQL in the request thread, the API would:
#   1. Block for many seconds (or minutes), timing out the tablet's HTTP request.
#   2. Become unresponsive to all OTHER tablets still trying to sync.
#   3. Risk losing the entire batch if the connection drops mid-write.
#
# SOLUTION — The Fire-and-Forget Pattern:
# The Flask sync endpoint does ONE thing: it drops the batch onto a Redis queue
# and immediately returns HTTP 202 Accepted to the tablet. The tablet is free.
# Celery worker processes pick up the batch from Redis in the background and
# insert records into PostgreSQL at their own pace without blocking anything.
#
# DATA FLOW:
#   Tablet  ──POST /sync/upload──►  Flask API  ──.delay()──►  Redis Queue
#                                       │                           │
#                                  202 Accepted          Celery Worker picks up
#                                  (instant)             ──► PostgreSQL INSERT
#
# IDEMPOTENCY GUARANTEE:
# Each AccessLog record has a pre-assigned UUID (generated by the tablet offline).
# The INSERT uses `INSERT ... ON CONFLICT (log_id) DO NOTHING`.
# Re-uploading the same batch (e.g., after a tablet retry) never creates duplicates.
# =============================================================================

import os
import json
import logging
from datetime import datetime, timezone

from celery import Celery
from celery.utils.log import get_task_logger

# Task-specific logger (separate from Flask's app logger)
logger = get_task_logger(__name__)


# =============================================================================
# Celery Application Factory
# =============================================================================

def make_celery(app=None):
    """
    Creates and configures the Celery application instance.

    This function uses the "factory" pattern mirroring Flask's create_app().
    When called with a Flask app instance, it binds Celery's task execution
    context to Flask's application context, making `db` and models available
    inside every task without additional setup.

    Args:
        app (Flask, optional): A Flask application instance. When provided,
            every Celery task runs inside Flask's app context automatically.
            If None, Celery runs standalone (used by the worker process).

    Returns:
        Celery: A configured Celery instance ready to dispatch and consume tasks.
    """

    # Read Redis URL from environment with a sensible local default.
    # In production, set REDIS_URL=redis://:password@host:6379/0
    redis_url = os.environ.get("REDIS_URL", "redis://localhost:6379/0")

    celery_app = Celery(
        # The main module name — must match the package where tasks are defined
        "jabu_sams",

        # BROKER: Redis is the message transport layer.
        # Flask API pushes task messages here via .delay() or .apply_async().
        broker=redis_url,

        # BACKEND: Redis also stores task state and results.
        # This lets us query whether a batch was processed successfully.
        backend=redis_url,

        # Auto-discover tasks defined in this module
        include=["app.celery_worker"],
    )

    # -------------------------------------------------------------------------
    # Celery Configuration
    # -------------------------------------------------------------------------
    celery_app.conf.update(
        # Serialize task arguments as JSON (not pickle) for security.
        # Pickle deserialization is a known remote code execution vector.
        task_serializer         = "json",
        result_serializer       = "json",
        accept_content          = ["json"],

        # Timezone: use UTC universally; the tablet's scan_timestamp already
        # carries timezone info from the device clock.
        timezone                = "UTC",
        enable_utc              = True,

        # Task retry policy: if a task fails (e.g., DB is momentarily down),
        # Celery will retry up to 3 times with exponential backoff.
        task_acks_late          = True,   # Acknowledge AFTER task completes, not before
        task_reject_on_worker_lost = True, # Re-queue if the worker crashes mid-task

        # Explicitly retain broker connection retry behaviour on startup.
        # Required to silence CPendingDeprecationWarning ahead of Celery 6.0,
        # where this will become the only way to enable startup retries.
        broker_connection_retry_on_startup = True,

        # Result expiry: keep task state in Redis for 24 hours for debugging,
        # then purge automatically.
        result_expires          = 86400,  # seconds (24 hours)

        # Worker concurrency: number of parallel worker processes.
        # Set to number of CPU cores. Override via --concurrency flag at startup.
        worker_concurrency      = 4,

        # Prefetch multiplier: how many tasks a worker reserves in advance.
        # 1 = fair scheduling (no worker hogs the queue). Ideal for uneven workloads.
        worker_prefetch_multiplier = 1,

        # Queue routing: all JABU-SAMS tasks route to the 'sync' queue.
        # In Phase 3+, we can add priority queues (e.g., 'security_flags').
        task_default_queue      = "jabu_sync",
        task_queues             = {
            "jabu_sync": {
                "exchange":      "jabu_sync",
                "routing_key":   "jabu_sync",
            },
        },
    )

    # -------------------------------------------------------------------------
    # Flask App Context Integration
    # -------------------------------------------------------------------------
    # This is the critical bridge between Celery and Flask.
    # Without this, Celery tasks cannot access `db.session` because Flask's
    # application context (which holds the DB connection) doesn't exist
    # in the worker process by default.
    if app is not None:
        class ContextTask(celery_app.Task):
            """
            A custom Celery Task base class that ensures every task execution
            is wrapped in a Flask application context.
            
            This means inside any @celery_app.task function, you can safely use:
              - db.session.add(...)
              - db.session.commit()
              - Any SQLAlchemy model query
            without manually calling app.app_context().
            """
            abstract = True  # This class itself is never a runnable task

            def __call__(self, *args, **kwargs):
                with app.app_context():
                    return self.run(*args, **kwargs)

        celery_app.Task = ContextTask

    return celery_app


# =============================================================================
# Standalone Celery Instance
# =============================================================================
# This instance is used when the worker process is launched via:
#   celery -A app.celery_worker.celery_app worker --loglevel=info -Q jabu_sync
#
# At that point, there is no Flask app running — the worker only loads this
# module. The Flask context integration is deferred until init_celery() is
# called from the Application Factory (which happens when the Flask API starts).
#
# The tasks defined below reference this instance via the @celery_app.task
# decorator and ARE available to both the worker and the Flask API dispatcher.

celery_app = make_celery()


# =============================================================================
# TASK: process_offline_batch
# =============================================================================

@celery_app.task(
    name        = "jabu_sams.process_offline_batch",
    bind        = True,          # `self` gives access to task metadata (retries, id)
    max_retries = 3,             # Retry up to 3 times on transient failures
    default_retry_delay = 30,    # Wait 30 seconds between retries
    queue       = "jabu_sync",
)
def process_offline_batch(self, batch_data: dict) -> dict:
    """
    Celery background task: persists a batch of offline tablet scan events.

    This is the ONLY function that writes AccessLog records from tablet sync
    uploads. It runs entirely in the background, decoupled from the HTTP
    request cycle. The Flask sync endpoint fires this task and returns
    immediately — this function handles the heavy lifting asynchronously.

    IDEMPOTENCY:
        Uses SQLAlchemy's INSERT ... ON CONFLICT DO NOTHING pattern.
        Re-processing the same batch_data (e.g., after a tablet retry) is
        completely safe — duplicate log_ids are silently skipped.

    FAULT ISOLATION:
        Individual malformed events are dropped with a WARNING log.
        A single bad record does NOT abort the entire batch.
        The task only fails (and triggers retry) on systemic errors like
        a database connection failure.

    Args:
        self:       Celery Task instance (injected by bind=True).
        batch_data: A dict with the structure:
                    {
                        "tablet_id":   "uuid-of-the-tablet-device",
                        "uploaded_at": "2026-05-29T08:00:00Z",
                        "events": [
                            {
                                "log_id":          "pre-assigned-uuid",
                                "user_id":         "uuid",
                                "guard_id":        "uuid",
                                "location":        "Main Gate",
                                "action_type":     "Entry",
                                "scan_timestamp":  "2026-05-29T07:45:00+01:00",
                                "luggage_photo_url": null,
                                "luggage_verified":  null,
                                "exit_token_expires_at": null,
                                "notes":           null,
                                "extra_data":      null
                            },
                            ...
                        ]
                    }

    Returns:
        dict: A summary report of the batch processing outcome:
              {
                  "task_id":   "celery-task-uuid",
                  "tablet_id": "...",
                  "total":     100,
                  "inserted":  98,
                  "skipped":   1,
                  "errors":    1
              }
    """
    # -------------------------------------------------------------------------
    # Import here (inside the task) to avoid circular imports at module level.
    # These imports work because Celery wraps this call in Flask's app context
    # (via the ContextTask base class defined in make_celery()).
    # -------------------------------------------------------------------------
    from app import db
    from app.models.core import AccessLog
    from sqlalchemy.dialects.postgresql import insert as pg_insert
    from sqlalchemy.exc import SQLAlchemyError

    task_id   = self.request.id
    tablet_id = batch_data.get("tablet_id", "unknown-tablet")
    events    = batch_data.get("events", [])

    logger.info(
        f"[Task {task_id}] Processing offline batch from tablet '{tablet_id}' "
        f"— {len(events)} events received."
    )

    # Counters for the summary report
    inserted = 0
    skipped  = 0   # Duplicate log_ids silently skipped
    errors   = 0   # Malformed individual records dropped

    for idx, event in enumerate(events):
        # -----------------------------------------------------------------
        # STEP 1: Validate the minimum required fields.
        # A malformed event is dropped with a warning; it does NOT abort
        # the batch. The remaining events continue processing.
        # -----------------------------------------------------------------
        required_fields = ["log_id", "user_id", "guard_id", "location",
                           "action_type", "scan_timestamp"]
        missing = [f for f in required_fields if not event.get(f)]
        if missing:
            logger.warning(
                f"[Task {task_id}] Event #{idx} dropped — missing fields: {missing}. "
                f"Raw event: {json.dumps(event)[:200]}"
            )
            errors += 1
            continue

        # -----------------------------------------------------------------
        # STEP 2: Parse and validate the scan_timestamp.
        # The tablet encodes this as an ISO 8601 string. We must parse it
        # to a timezone-aware datetime object for PostgreSQL TIMESTAMPTZ.
        # -----------------------------------------------------------------
        try:
            scan_ts = datetime.fromisoformat(event["scan_timestamp"])
            # Ensure the timestamp is timezone-aware (normalize to UTC)
            if scan_ts.tzinfo is None:
                # Tablet clock had no timezone — assume UTC as a safe fallback
                scan_ts = scan_ts.replace(tzinfo=timezone.utc)
                logger.warning(
                    f"[Task {task_id}] Event #{idx} (log_id={event['log_id']}) "
                    f"has no timezone in scan_timestamp. Defaulting to UTC."
                )
        except (ValueError, TypeError) as e:
            logger.warning(
                f"[Task {task_id}] Event #{idx} dropped — invalid scan_timestamp "
                f"'{event.get('scan_timestamp')}': {e}"
            )
            errors += 1
            continue

        # -----------------------------------------------------------------
        # STEP 3: Parse optional exit_token_expires_at (nullable field).
        # -----------------------------------------------------------------
        exit_expires = None
        if event.get("exit_token_expires_at"):
            try:
                exit_expires = datetime.fromisoformat(event["exit_token_expires_at"])
            except (ValueError, TypeError):
                logger.warning(
                    f"[Task {task_id}] Event #{idx} — invalid exit_token_expires_at, "
                    f"storing as NULL."
                )
                # Non-fatal: store as NULL rather than dropping the event

        # -----------------------------------------------------------------
        # STEP 4: Build the INSERT statement with ON CONFLICT DO NOTHING.
        #
        # This is the idempotency guarantee:
        # If this exact log_id already exists in PostgreSQL (because this
        # batch was uploaded before), the INSERT is silently skipped.
        # The `result.rowcount` tells us if the row was actually inserted.
        # -----------------------------------------------------------------
        try:
            stmt = (
                pg_insert(AccessLog.__table__)
                .values(
                    log_id                = event["log_id"],
                    user_id               = event["user_id"],
                    guard_id              = event["guard_id"],
                    location              = event["location"],
                    action_type           = event["action_type"],
                    scan_timestamp        = scan_ts,
                    # server_timestamp: set to NOW() by the server on receipt —
                    # this is when the CLOUD processed it, not when it was scanned.
                    server_timestamp      = datetime.now(timezone.utc),
                    luggage_photo_url     = event.get("luggage_photo_url"),
                    luggage_verified      = event.get("luggage_verified"),
                    exit_token_expires_at = exit_expires,
                    notes                 = event.get("notes"),
                    extra_data            = event.get("extra_data"),
                )
                .on_conflict_do_nothing(index_elements=["log_id"])
                # ON CONFLICT (log_id) DO NOTHING:
                # If this UUID already exists → skip silently (idempotent).
                # If it's new → insert normally.
            )

            result = db.session.execute(stmt)

            if result.rowcount == 1:
                inserted += 1
            else:
                # rowcount == 0 means the log_id already existed → duplicate
                skipped += 1
                logger.debug(
                    f"[Task {task_id}] Event #{idx} (log_id={event['log_id']}) "
                    f"already exists — skipped (idempotent)."
                )

        except SQLAlchemyError as e:
            # A single record's DB error is isolated — log it and continue.
            # The session is rolled back for this statement only (savepoint).
            db.session.rollback()
            logger.error(
                f"[Task {task_id}] DB error on event #{idx} "
                f"(log_id={event.get('log_id')}): {e}"
            )
            errors += 1
            continue

    # -------------------------------------------------------------------------
    # STEP 5: Commit the entire batch as a single transaction.
    # This is done ONCE after the loop for maximum efficiency.
    # If the final commit fails (e.g., DB connection dropped), Celery will
    # retry the entire task (safe because of ON CONFLICT DO NOTHING).
    # -------------------------------------------------------------------------
    try:
        db.session.commit()
    except SQLAlchemyError as exc:
        db.session.rollback()
        logger.error(
            f"[Task {task_id}] Final commit failed for batch from '{tablet_id}': {exc}. "
            f"Retrying task..."
        )
        # Raise to trigger Celery's retry mechanism with exponential backoff
        raise self.retry(exc=exc, countdown=30 * (self.request.retries + 1))

    # -------------------------------------------------------------------------
    # STEP 6: Build and return the summary report.
    # This is stored in Redis as the task result and retrievable via task_id.
    # -------------------------------------------------------------------------
    summary = {
        "task_id":   task_id,
        "tablet_id": tablet_id,
        "total":     len(events),
        "inserted":  inserted,
        "skipped":   skipped,   # Duplicates silently ignored
        "errors":    errors,    # Malformed records dropped
    }

    logger.info(
        f"[Task {task_id}] Batch complete — "
        f"Total: {len(events)} | Inserted: {inserted} | "
        f"Skipped (dup): {skipped} | Errors: {errors}"
    )

    return summary
